# docker-compose.yml
version: "3"
services:
  postgres:
    image: postgres:10.10-alpine
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "5430:5432"
volumes:
  postgres-data:
